- hosts: retrosheet
  user: vagrant
  sudo: yes
  vars:
    chadwick: "http://sourceforge.net/projects/chadwick/files/chadwick-0.6/chadwick-0.6.4/chadwick-0.6.4.tar.gz"
    work_dir: "/tmp"
    chadwick_dir: "chadwick-0.6.4"
    py_retrosheet_script_dir: "/vagrant/py-retrosheet/scripts"
    years:
      - 2014
      - 2013
  tasks:
  - name: get chadwick 
    shell: wget {{ chadwick }} chdir={{ work_dir }}
  - shell: tar zxvf chadwick-0.6.4.tar.gz chdir={{ work_dir }}
  - name: build chadwick 
    shell: ./configure chdir="{{ work_dir }}/{{ chadwick_dir }}"
  - shell: make chdir="{{ work_dir }}/{{ chadwick_dir }}"
  - shell: make install chdir="{{ work_dir }}/{{ chadwick_dir }}"
  - shell: ln -s /usr/local/lib/libchadwick.so.0 /usr/lib/libchadwick.so.0
  - name: download events & game data
    shell: python download.py -y {{ item }} chdir={{ py_retrosheet_script_dir }}
    with_items: years
  - name: create retrosheet database
    shell: python parse.py -y {{ item }} chdir={{ py_retrosheet_script_dir }}
    with_items: years
