- hosts: retrosheet
  user: vagrant
  sudo: yes
  vars:
    py_retrosheet: "https://github.com/wellsoliver/py-retrosheet.git"
    work_dir: "/vagrant"
    host: "localhost"
    mysql_database: "retrosheet"
    mysql_schema_sql: "py-retrosheet/sql/schema.sql"
    mysql_index_sql: "create_index.sql"
    py_retrosheet_config: "py-retrosheet/scripts/config.ini"
  vars_prompt:
    mysql_root_db_password: "MySQL root password"
    mysql_app_db_password: "MySQL app password"
  tasks:
  - name: Apt install packages
    apt: update_cache=yes pkg={{ item }}
    with_items:
      - git
      - python-pip
      - python-mysqldb
      - python-sqlalchemy
      - mysql-server-5.6
  - name: MySQL root user settings
    mysql_user: name=root password={{ mysql_root_db_password }}
  - name: MySQL create database
    mysql_db: login_user=root login_password={{ mysql_root_db_password }} name={{ mysql_database }} state=present encoding=utf8
  - name: MySQL create app user
    mysql_user: login_user=root login_password={{ mysql_root_db_password }} name=app password={{ mysql_app_db_password }} priv=retrosheet.*:ALL,GRANT host=% state=present
  - name: Apt upgrade
    apt: upgrade=dist
  - name: copy my.cnf
    template: src="templates/my.cnf" dest=/etc/mysql/my.cnf owner=root mode=0600
  - name: Restart the MySQL service
    service: name=mysql state=restarted enabled=true
  - name: clone project for py-retrosheet
    shell: git clone {{ py_retrosheet }} chdir={{ work_dir }}
  - name: create py_retrosheet config.ini
    template: src="templates/py_retrosheet_config.ini" dest="{{ work_dir }}/{{ py_retrosheet_config }}"
  - name: MySQL create schema
    mysql_db: login_user=root login_password={{ mysql_root_db_password }} name={{ mysql_database }} target="{{ work_dir }}/{{ mysql_schema_sql }}" state=import
  - name: MySQL create index
    mysql_db: login_user=root login_password={{ mysql_root_db_password }} name={{ mysql_database }} target="{{ work_dir }}/{{ mysql_index_sql }}" state=import
