- hosts: retrosheet
  user: vagrant
  sudo: yes
  vars:
    py_retrosheet: "https://github.com/wellsoliver/py-retrosheet.git"
    work_dir: "/vagrant"
    host: "localhost"
    mysql_database: "retrosheet"
    mysql_schema_sql: "/vagrant/py-retrosheet/sql/schema.sql"
    mysql_index_sql: "/vagrant/create_index.sql"
  vars_prompt:
    mysql_root_db_password: "MySQL root password"
    mysql_app_db_password: "MySQL app password"
  tasks:
  - name: Apt install packages
    apt: update_cache=yes pkg={{ item }}
    with_items:
      - git
      - python-pip
      - python-mysqldb
      - python-sqlalchemy
      - mysql-server-5.6
  - name: MySQL root user settings
    mysql_user: name=root password={{ mysql_root_db_password }}
  - name: MySQL create database
    mysql_db: login_user=root login_password={{ mysql_root_db_password }} name={{ mysql_database }} state=present encoding=utf8
  - name: MySQL create app user
    mysql_user: login_user=root login_password={{ mysql_root_db_password }} name=app password={{ mysql_app_db_password }} priv=retrosheet.*:ALL,GRANT host=% state=present
  - name: Apt upgrade
    apt: upgrade=dist
  - name: copy my.cnf
    copy: src=my.cnf dest=/etc/mysql/my.cnf owner=root mode=0600
  - name: Restart the MySQL service
    service: name=mysql state=restarted enabled=true
  - name: clone project for py-retrosheet
    shell: git clone {{ py_retrosheet }} chdir={{ work_dir }}
  - name: MySQL create schema
    mysql_db: login_user=root login_password={{ mysql_root_db_password }} name={{ mysql_database }} target={{ mysql_schema_sql }} state=import
  - name: MySQL create index
    mysql_db: login_user=root login_password={{ mysql_root_db_password }} name={{ mysql_database }} target={{ mysql_index_sql }} state=import
