---
- name: MySQL root user settings
  mysql_user: name=root password={{ mysql_root_db_password }}
- name: MySQL create database
  mysql_db: login_user=root login_password={{ mysql_root_db_password }} name={{ mysql_database }} state=present encoding=utf8
- name: MySQL create app user
  mysql_user: login_user=root login_password={{ mysql_root_db_password }} name=app password={{ mysql_app_db_password }} priv=retrosheet.*:ALL,GRANT host=% state=present
- name: copy my.cnf
  template: src="tasks/templates/my.cnf" dest=/etc/mysql/my.cnf owner=root mode=0600
- name: Restart the MySQL service
  service: name=mysql state=restarted enabled=true
- name: MySQL create schema
  mysql_db: login_user=root login_password={{ mysql_root_db_password }} name={{ mysql_database }} target="{{ work_dir }}/{{ mysql_schema_sql }}" state=import
- name: MySQL create index
  mysql_db: login_user=root login_password={{ mysql_root_db_password }} name={{ mysql_database }} target="{{ vagrant_dir }}/{{ mysql_index_sql }}" state=import
- name: Restart the MySQL service
  service: name=mysql state=restarted enabled=true
